// Erzeugt aus den Beitraegen von adhs.expert, Stand 24. August 2026.
// Jeder Eintrag ist ein Beitrag, dessen PDF-Text jetzt vollstaendig
// im Beitrag selbst steht. Das Feld `ocr` markiert die Faelle, deren PDF ein
// Scan ohne Textebene war und per Tesseract erkannt wurde.

pub struct Eintrag {
    pub datum: &'static str,
    pub titel: &'static str,
    pub url: &'static str,
    pub woerter: u32,
    pub ocr: bool,
}

pub const EINTRAEGE: &[Eintrag] = &[
    Eintrag {
        datum: "18.06.2026",
        titel: "Wir sollten keine Kamelgesellschaft haben mit zwei Höckern",
        url: "https://adhs.expert/2026/06/18/wir-sollten-keine-kamelgesellschaft-haben-mit-zwei-hoeckern/",
        woerter: 2841,
        ocr: false,
    },
    Eintrag {
        datum: "17.06.2026",
        titel: "ADHS ist keine Mode. Gene werden vererbt.",
        url: "https://adhs.expert/2026/06/17/adhs-ist-keine-mode-gene-werden-vererbt/",
        woerter: 9993,
        ocr: false,
    },
    Eintrag {
        datum: "15.06.2026",
        titel: "Zentrum menschlicher Gefühle Teil 2",
        url: "https://adhs.expert/2026/06/15/zentrum-menschlicher-gefuehle-teil-2/",
        woerter: 10530,
        ocr: false,
    },
    Eintrag {
        datum: "10.06.2026",
        titel: "Zentrum menschlicher Gefühle",
        url: "https://adhs.expert/2026/06/10/zentrum-menschlicher-gefuehle/",
        woerter: 7960,
        ocr: false,
    },
    Eintrag {
        datum: "31.05.2026",
        titel: "ADHS ist keine Krankheit",
        url: "https://adhs.expert/2026/05/31/adhs-ist-keine-krankheit-2/",
        woerter: 9820,
        ocr: false,
    },
    Eintrag {
        datum: "28.05.2026",
        titel: "Was sind die speziellen Herausforderungen bei ADHS?",
        url: "https://adhs.expert/2026/05/28/was-sind-die-speziellen-herausforderungen-bei-adhs/",
        woerter: 16274,
        ocr: false,
    },
    Eintrag {
        datum: "13.05.2026",
        titel: "Psychische Krankheiten",
        url: "https://adhs.expert/2026/05/13/psychische-krankheiten/",
        woerter: 7974,
        ocr: false,
    },
    Eintrag {
        datum: "12.04.2026",
        titel: "Erziehungsschäden – Teil 4",
        url: "https://adhs.expert/2026/04/12/erziehungsschaeden-teil-4/",
        woerter: 3998,
        ocr: false,
    },
    Eintrag {
        datum: "11.04.2026",
        titel: "Erziehungsschäden Teil 3",
        url: "https://adhs.expert/2026/04/11/erziehungsschaeden-teil-3/",
        woerter: 9336,
        ocr: false,
    },
    Eintrag {
        datum: "09.04.2026",
        titel: "Erziehungsschäden Teil 2",
        url: "https://adhs.expert/2026/04/09/erziehungsschaeden-teil-2/",
        woerter: 8612,
        ocr: false,
    },
    Eintrag {
        datum: "01.04.2026",
        titel: "Erziehungsschäden",
        url: "https://adhs.expert/2026/04/01/erziehungsschaeden/",
        woerter: 6470,
        ocr: false,
    },
    Eintrag {
        datum: "08.02.2026",
        titel: "Emotionskontrolle",
        url: "https://adhs.expert/2026/02/08/emotionskontrolle/",
        woerter: 10015,
        ocr: false,
    },
    Eintrag {
        datum: "28.01.2026",
        titel: "Jugend heute",
        url: "https://adhs.expert/2026/01/28/jugend-heute/",
        woerter: 812,
        ocr: false,
    },
    Eintrag {
        datum: "08.01.2026",
        titel: "Zusammenarbeit statt Kompetition",
        url: "https://adhs.expert/2026/01/08/zusammenarbeit-statt-kompetition/",
        woerter: 6417,
        ocr: false,
    },
    Eintrag {
        datum: "23.12.2025",
        titel: "Genetische Vererbung ist keine Mode",
        url: "https://adhs.expert/2025/12/23/genetische-vererbung-ist-keine-mode/",
        woerter: 6575,
        ocr: false,
    },
    Eintrag {
        datum: "12.10.2025",
        titel: "Rigi Apoheke und Drogerie Buchvernissage Dr.med. Ursula Davatz",
        url: "https://adhs.expert/2025/10/12/rigi-apoheke-und-drogerie-buchvernissage-dr-med-ursula-davatz/",
        woerter: 7432,
        ocr: false,
    },
    Eintrag {
        datum: "01.10.2025",
        titel: "Wir sollten von den Patienten lernen",
        url: "https://adhs.expert/2025/10/01/wir-sollten-von-den-patienten-lernen/",
        woerter: 1372,
        ocr: false,
    },
    Eintrag {
        datum: "16.07.2025",
        titel: "Wie geht man als Erziehungsperson mit ADHS/ADS Kindern um?",
        url: "https://adhs.expert/2025/07/16/wie-geht-man-als-erziehungsperson-mit-adhs-ads-kindern-um/",
        woerter: 11888,
        ocr: false,
    },
    Eintrag {
        datum: "10.06.2025",
        titel: "Die Geschichte der Sozialpsychiatrie in der Schweiz",
        url: "https://adhs.expert/2025/06/10/die-geschichte-der-sozialpsychiatrie-in-der-schweiz/",
        woerter: 7171,
        ocr: false,
    },
    Eintrag {
        datum: "06.06.2025",
        titel: "Podium über Frauen zum Thema ADHS/ADS",
        url: "https://adhs.expert/2025/06/06/podium-ueber-frauen-zum-thema-adhs-ads/",
        woerter: 13436,
        ocr: false,
    },
    Eintrag {
        datum: "23.05.2025",
        titel: "Erziehungsstil, Emotionskontrolle",
        url: "https://adhs.expert/2025/05/23/erziehungsstil-emotionskontrolle/",
        woerter: 10849,
        ocr: false,
    },
    Eintrag {
        datum: "27.04.2025",
        titel: "Umgang mit ADHS/ADS im Klinikalltag",
        url: "https://adhs.expert/2025/04/27/umgang-mit-adhs-ads-im-klinikalltag/",
        woerter: 13614,
        ocr: false,
    },
    Eintrag {
        datum: "14.04.2025",
        titel: "30-jähriges Jubiläum des Zentrums für Psychiatrie und Psychotherapie ambulant (ZPPA)",
        url: "https://adhs.expert/2025/04/14/30-jaehriges-jubilaeum-des-zentrums-fuer-psychiatrie-und-psychotherapie-ambulant-zppa/",
        woerter: 4185,
        ocr: false,
    },
    Eintrag {
        datum: "10.04.2025",
        titel: "Immer mehr psychisch kranke Jugendliche. Was läuft schief?",
        url: "https://adhs.expert/2025/04/10/immer-mehr-psychisch-kranke-jugendliche-was-laeuft-schief/",
        woerter: 25178,
        ocr: false,
    },
    Eintrag {
        datum: "27.03.2025",
        titel: "Autismusdiagnostik auf neurologischer Ebene",
        url: "https://adhs.expert/2025/03/27/autismusdiagnostik-auf-neurologischer-ebene/",
        woerter: 6909,
        ocr: false,
    },
    Eintrag {
        datum: "24.03.2025",
        titel: "Ein Gespräch mit Dr. Marcel Bertschi",
        url: "https://adhs.expert/2025/03/24/ein-gespraech-mit-dr-marcel-bertschi/",
        woerter: 4870,
        ocr: false,
    },
    Eintrag {
        datum: "15.03.2025",
        titel: "Elternabend zum Thema Umgang mit ADHS/ADS",
        url: "https://adhs.expert/2025/03/15/elternabend-zum-thema-umgang-mit-adhs-ads/",
        woerter: 9413,
        ocr: false,
    },
    Eintrag {
        datum: "09.12.2024",
        titel: "50 Jahre Begleitung von Familien und Personen mit ADHS/ADS",
        url: "https://adhs.expert/2024/12/09/50-jahre-begleitung-von-familien-und-personen-mit-adhs-ads/",
        woerter: 3035,
        ocr: false,
    },
    Eintrag {
        datum: "07.12.2024",
        titel: "ADHS und Schule mit Sammy Frey",
        url: "https://adhs.expert/2024/12/07/adhs-und-schule-mit-sammy-frey/",
        woerter: 7741,
        ocr: false,
    },
    Eintrag {
        datum: "01.12.2024",
        titel: "ADHS/ADS – Grenzzerfall",
        url: "https://adhs.expert/2024/12/01/adhs-ads-grenzzerfall/",
        woerter: 7014,
        ocr: false,
    },
    Eintrag {
        datum: "27.11.2024",
        titel: "Autismus Spektrum Störung",
        url: "https://adhs.expert/2024/11/27/autismus-spektrum-stoerung/",
        woerter: 6040,
        ocr: false,
    },
    Eintrag {
        datum: "20.11.2024",
        titel: "Autismus-Spektrum Persönlichkeit",
        url: "https://adhs.expert/2024/11/20/autismus-spektrum-persoenlichkeit/",
        woerter: 6535,
        ocr: false,
    },
    Eintrag {
        datum: "26.10.2024",
        titel: "ADHS bei Erwachsenen – Auswirkungen auf Beruf und psychische Gesundheit",
        url: "https://adhs.expert/2024/10/26/adhs-bei-erwachsenen-auswirkungen-auf-beruf-und-psychische-gesundheit/",
        woerter: 3949,
        ocr: false,
    },
    Eintrag {
        datum: "05.10.2024",
        titel: "Umgang mit ADHS/ADS im Erwachsenenalter",
        url: "https://adhs.expert/2024/10/05/umgang-mit-adhs-ads-im-erwachsenenalter/",
        woerter: 11425,
        ocr: false,
    },
    Eintrag {
        datum: "25.09.2024",
        titel: "ADHS/ADS: mehr als eine Modediagnose?",
        url: "https://adhs.expert/2024/09/25/adhs-ads-mehr-als-eine-modediagnose/",
        woerter: 4790,
        ocr: false,
    },
    Eintrag {
        datum: "22.09.2024",
        titel: "Wie geht man als ErzieherIn mit ADHS und ADS Kindern um?",
        url: "https://adhs.expert/2024/09/22/wie-geht-man-als-erzieherin-mit-adhs-und-ads-kindern-um/",
        woerter: 10817,
        ocr: false,
    },
    Eintrag {
        datum: "11.09.2024",
        titel: "Grosseltern",
        url: "https://adhs.expert/2024/09/11/grosseltern/",
        woerter: 11923,
        ocr: false,
    },
    Eintrag {
        datum: "02.09.2024",
        titel: "Second Life",
        url: "https://adhs.expert/2024/09/02/second-life/",
        woerter: 1394,
        ocr: false,
    },
    Eintrag {
        datum: "09.07.2024",
        titel: "Zeitungsartikel zum Thema ADHS/ADS",
        url: "https://adhs.expert/2024/07/09/zeitungsartikel-zum-thema-adhs-ads/",
        woerter: 1461,
        ocr: false,
    },
    Eintrag {
        datum: "27.06.2024",
        titel: "Posttraumatische Belastungsstörung – PTBS",
        url: "https://adhs.expert/2024/06/27/posttraumatische-belastungsstoerung-ptbs-2/",
        woerter: 6618,
        ocr: false,
    },
    Eintrag {
        datum: "14.06.2024",
        titel: "Umgang mit ADHS/ADS, Schule am Wasser",
        url: "https://adhs.expert/2024/06/14/umgang-mit-adhs-ads-schule-am-wasser/",
        woerter: 8603,
        ocr: false,
    },
    Eintrag {
        datum: "03.06.2024",
        titel: "Posttraumatische Belastungsstörung (PTBS)",
        url: "https://adhs.expert/2024/06/03/posttraumatische-belastungsstoerung-ptbs/",
        woerter: 7590,
        ocr: false,
    },
    Eintrag {
        datum: "10.04.2024",
        titel: "Apéro zum Thema ADHS/ADS",
        url: "https://adhs.expert/2024/04/10/apero-zum-thema-adhs-ads/",
        woerter: 5487,
        ocr: false,
    },
    Eintrag {
        datum: "26.03.2024",
        titel: "Kritik, Frust, Enttäuschung und Motivationslosigkeit bei Jugendlichen und jungen Erwachsenen.",
        url: "https://adhs.expert/2024/03/26/kritik-frust-enttaeuschung-und-motivationslosigkeit-bei-jugendlichen-und-jungen-erwachsenen/",
        woerter: 7977,
        ocr: false,
    },
    Eintrag {
        datum: "22.03.2024",
        titel: "Gesellschaft unter Hochdruck",
        url: "https://adhs.expert/2024/03/22/gesellschaft-unter-hochdruck/",
        woerter: 7763,
        ocr: false,
    },
    Eintrag {
        datum: "20.03.2024",
        titel: "Hochstrittige Eltern",
        url: "https://adhs.expert/2024/03/20/hochstrittige-eltern/",
        woerter: 8068,
        ocr: false,
    },
    Eintrag {
        datum: "13.03.2024",
        titel: "Vulnerabilität – Erziehung – Krankheit",
        url: "https://adhs.expert/2024/03/13/vulnerabilitaet-erziehung-krankheit/",
        woerter: 7462,
        ocr: false,
    },
    Eintrag {
        datum: "02.03.2024",
        titel: "Kaboom Room mit Fabienne Hadorn zum Thema ADHS/ADS",
        url: "https://adhs.expert/2024/03/02/kaboom-room-mit-fabienne-hadorn-zum-thema-adhs-ads/",
        woerter: 3767,
        ocr: false,
    },
    Eintrag {
        datum: "26.02.2024",
        titel: "Frust und Enttäuschung",
        url: "https://adhs.expert/2024/02/26/frust-und-enttaeuschung/",
        woerter: 7754,
        ocr: false,
    },
    Eintrag {
        datum: "25.02.2024",
        titel: "Replik zum Interview mit Dagmar Rösler im Sonntagsblick",
        url: "https://adhs.expert/2024/02/25/replik-zum-interview-mit-dagmar-roesler-im-sonntagsblick/",
        woerter: 2205,
        ocr: false,
    },
    Eintrag {
        datum: "16.12.2023",
        titel: "ADHS bei Erwachsenen, Anpassung bis zum Burnout",
        url: "https://adhs.expert/2023/12/16/adhs-bei-erwachsenen-anpassung-bis-zum-burnout/",
        woerter: 3101,
        ocr: false,
    },
    Eintrag {
        datum: "12.12.2023",
        titel: "Weltanschauliches, Therapeutisches und Persönliches",
        url: "https://adhs.expert/2023/12/12/weltanschauliches-therapeutisches-und-persoenliches/",
        woerter: 8102,
        ocr: false,
    },
    Eintrag {
        datum: "05.12.2023",
        titel: "Substanzmissbrauch und Handling im Arbeitskontext",
        url: "https://adhs.expert/2023/12/05/substanzmissbrauch-und-handling-im-arbeitskontext-2/",
        woerter: 8675,
        ocr: false,
    },
    Eintrag {
        datum: "04.12.2023",
        titel: "ADHS, ADS, Hypersensibilität und Autismus",
        url: "https://adhs.expert/2023/12/04/adhs-ads-hypersensibilitaet-und-autismus/",
        woerter: 5396,
        ocr: false,
    },
    Eintrag {
        datum: "30.11.2023",
        titel: "Umgang mit ADHS/ADS Kindern",
        url: "https://adhs.expert/2023/11/30/umgang-mit-adhs-ads-kindern/",
        woerter: 16493,
        ocr: false,
    },
    Eintrag {
        datum: "22.11.2023",
        titel: "Substanzmissbrauch und Handling im Arbeitskontext",
        url: "https://adhs.expert/2023/11/22/substanzmissbrauch-und-handling-im-arbeitskontext/",
        woerter: 8511,
        ocr: false,
    },
    Eintrag {
        datum: "15.11.2023",
        titel: "Temperament gerechter Umgang",
        url: "https://adhs.expert/2023/11/15/temperament-gerechter-umgang/",
        woerter: 12275,
        ocr: false,
    },
    Eintrag {
        datum: "24.09.2023",
        titel: "Schulabsentismus",
        url: "https://adhs.expert/2023/09/24/schulabsentismus/",
        woerter: 12900,
        ocr: false,
    },
    Eintrag {
        datum: "07.09.2023",
        titel: "Where does Schizophrenia come from?",
        url: "https://adhs.expert/2023/09/07/where-does-schizophrenia-come-from/",
        woerter: 8045,
        ocr: false,
    },
    Eintrag {
        datum: "26.07.2023",
        titel: "Autismus und Psychiatrie – Was wenn nichts mehr geht?",
        url: "https://adhs.expert/2023/07/26/autismus-und-psychiatrie-was-wenn-nichts-mehr-geht/",
        woerter: 5559,
        ocr: false,
    },
    Eintrag {
        datum: "28.06.2023",
        titel: "Umgang mit ADHS, Anleitung für Betroffene, Angehörige und Fachpersonen",
        url: "https://adhs.expert/2023/06/28/umgang-mit-adhs-anleitung-fuer-betroffene-angehoerige-und-fachpersonen/",
        woerter: 3782,
        ocr: false,
    },
    Eintrag {
        datum: "26.06.2023",
        titel: "Narzissmus und persönliche Identität, zweiter Vortrag",
        url: "https://adhs.expert/2023/06/26/narzissmus-und-persoenliche-identitaet-zweiter-vortrag/",
        woerter: 8299,
        ocr: false,
    },
    Eintrag {
        datum: "15.06.2023",
        titel: "Narzissmus und persönliche Identität",
        url: "https://adhs.expert/2023/06/15/narzissmus-und-persoenliche-identitaet/",
        woerter: 7289,
        ocr: false,
    },
    Eintrag {
        datum: "26.05.2023",
        titel: "ADHS und psychiatrische Folgeerkrankungen",
        url: "https://adhs.expert/2023/05/26/adhs-und-psychiatrische-folgeerkrankungen/",
        woerter: 5647,
        ocr: false,
    },
    Eintrag {
        datum: "11.02.2023",
        titel: "Selbstwert und Selbstvertrauen im Kontext der Berufsfindung und Berufsausübung",
        url: "https://adhs.expert/2023/02/11/selbstwert-und-selbstvertrauen-im-kontext-der-berufsfindung-und-berufsausuebung/",
        woerter: 7422,
        ocr: false,
    },
    Eintrag {
        datum: "10.02.2023",
        titel: "ADHS und Selbsterziehung: Prägungen und Erwartungen",
        url: "https://adhs.expert/2023/02/10/adhs-und-selbsterziehung-praegungen-und-erwartungen-2/",
        woerter: 2457,
        ocr: false,
    },
    Eintrag {
        datum: "18.01.2023",
        titel: "Neues in der Schizophrenie und ADHS Behandlung",
        url: "https://adhs.expert/2023/01/18/neues-in-der-schizophrenie-und-adhs-behandlung/",
        woerter: 10739,
        ocr: false,
    },
    Eintrag {
        datum: "14.12.2022",
        titel: "Berufliches Scheitern, Krise, Gefahr, Chance",
        url: "https://adhs.expert/2022/12/14/krise-gefahr-chance/",
        woerter: 7149,
        ocr: false,
    },
    Eintrag {
        datum: "21.11.2022",
        titel: "Temperamentgerechte, innovative Kinderbegleitung",
        url: "https://adhs.expert/2022/11/21/temperamentgerechte-innovative-kinderbegleitung/",
        woerter: 3603,
        ocr: false,
    },
    Eintrag {
        datum: "21.11.2022",
        titel: "HotA als Erziehungsmediation zwischen Kind, Eltern und Schule",
        url: "https://adhs.expert/2022/11/21/hota-als-erziehungsmediation-zwischen-kind-eltern-und-schule/",
        woerter: 4456,
        ocr: false,
    },
    Eintrag {
        datum: "14.11.2022",
        titel: "ADHS bei Erwachsenen: «Wer ADHS hat, kann Berge versetzen»",
        url: "https://adhs.expert/2022/11/14/adhs-bei-erwachsenen-wer-adhs-hat-kann-berge-versetzen/",
        woerter: 944,
        ocr: false,
    },
    Eintrag {
        datum: "19.09.2022",
        titel: "Herkunftssystem von Pflegekindern, Genderthematik",
        url: "https://adhs.expert/2022/09/19/herkunftssystem-von-pflegekindern-genderthematik/",
        woerter: 17924,
        ocr: false,
    },
    Eintrag {
        datum: "14.09.2022",
        titel: "Studieren mit ADHS – was bedeutet dies für die Lehre?",
        url: "https://adhs.expert/2022/09/14/studieren-mit-adhs-was-bedeutet-dies-fuer-die-lehre/",
        woerter: 9684,
        ocr: false,
    },
    Eintrag {
        datum: "16.08.2022",
        titel: "«Mir war immer klar, dass ich etwas anders bin»",
        url: "https://adhs.expert/2022/08/16/mir-war-immer-klar-dass-ich-etwas-anders-bin/",
        woerter: 2712,
        ocr: false,
    },
    Eintrag {
        datum: "15.08.2022",
        titel: "Vererbte Verwirrung",
        url: "https://adhs.expert/2022/08/15/vererbte-verwirrung/",
        woerter: 2795,
        ocr: false,
    },
    Eintrag {
        datum: "15.06.2022",
        titel: "Borderline Persönlichkeitsstörung",
        url: "https://adhs.expert/2022/06/15/borderline-persoenlichkeitsstoerung/",
        woerter: 6561,
        ocr: false,
    },
    Eintrag {
        datum: "15.06.2022",
        titel: "Geschichte der Sozialpsychiatrie bezogen auf die aufsuchende Familienarbeit",
        url: "https://adhs.expert/2022/06/15/geschichte-der-sozialpsychiatrie-bezogen-auf-die-aufsuchende-familienarbeit/",
        woerter: 2993,
        ocr: false,
    },
    Eintrag {
        datum: "25.05.2022",
        titel: "Wie und wann entgleisen Jugendliche mit AD(H)S in eine psychische Krankheit?",
        url: "https://adhs.expert/2022/05/25/wie-und-wann-entgleisen-jugendliche-mit-adhs-in-eine-psychische-krankheit-3/",
        woerter: 3388,
        ocr: false,
    },
    Eintrag {
        datum: "07.05.2022",
        titel: "Sie hat im Aargau Spuren hinterlassen",
        url: "https://adhs.expert/2022/05/07/sie-hat-im-aargau-spuren-hinterlassen/",
        woerter: 1268,
        ocr: false,
    },
    Eintrag {
        datum: "04.05.2022",
        titel: "Umgang mit Kindern aus schwierigem privatem Umfeld",
        url: "https://adhs.expert/2022/05/04/umgang-mit-kindern-aus-schwierigem-privatem-umfeld/",
        woerter: 3782,
        ocr: false,
    },
    Eintrag {
        datum: "04.05.2022",
        titel: "Wann lässt die Seele den Körper sprechen",
        url: "https://adhs.expert/2022/05/04/wann-laesst-die-seele-den-koerper-sprechen/",
        woerter: 16724,
        ocr: false,
    },
    Eintrag {
        datum: "27.03.2022",
        titel: "Selektiver Mutismus und Schulverweigerung",
        url: "https://adhs.expert/2022/03/27/selektiver-mutismus-und-schulverweigerung/",
        woerter: 7911,
        ocr: false,
    },
    Eintrag {
        datum: "27.03.2022",
        titel: "Psychische Krankheiten aus der Herkunftsfamilie",
        url: "https://adhs.expert/2022/03/27/psychische-krankheiten-aus-der-herkunftsfamilie/",
        woerter: 16805,
        ocr: false,
    },
    Eintrag {
        datum: "08.03.2022",
        titel: "Das weibliche ADHS",
        url: "https://adhs.expert/2022/03/08/das-weibliche-adhs/",
        woerter: 1344,
        ocr: false,
    },
    Eintrag {
        datum: "13.02.2022",
        titel: "Autismus, Menschen mit Hochsensibilität",
        url: "https://adhs.expert/2022/02/13/autismus-menschen-mit-hochsensibilitaet/",
        woerter: 7853,
        ocr: false,
    },
    Eintrag {
        datum: "13.02.2022",
        titel: "ADHS und ADS bei Jugendlichen und Erwachsenen",
        url: "https://adhs.expert/2022/02/13/adhs-und-ads-bei-jugendlichen-und-erwachsenen/",
        woerter: 6529,
        ocr: false,
    },
    Eintrag {
        datum: "18.11.2021",
        titel: "Mit ADHS leben lernen",
        url: "https://adhs.expert/2021/11/18/mit-adhs-leben-lernen/",
        woerter: 1001,
        ocr: false,
    },
    Eintrag {
        datum: "15.11.2021",
        titel: "Psychiatrie wohin?",
        url: "https://adhs.expert/2021/11/15/psychiatrie-wohin/",
        woerter: 2338,
        ocr: false,
    },
    Eintrag {
        datum: "23.10.2021",
        titel: "Wie unsere Herkunftsfamilie uns prägt",
        url: "https://adhs.expert/2021/10/23/wie-unsere-herkunftsfamilie-uns-praegt-2/",
        woerter: 6286,
        ocr: false,
    },
    Eintrag {
        datum: "05.10.2021",
        titel: "Was braucht es für die Ausbildung unserer nächsten Generation?",
        url: "https://adhs.expert/2021/10/05/was-braucht-es-fuer-die-ausbildung-unserer-naechsten-generation-2/",
        woerter: 7979,
        ocr: false,
    },
    Eintrag {
        datum: "05.10.2021",
        titel: "Podcast: Welche Schulen brauchen die Kinder von heute?",
        url: "https://adhs.expert/2021/10/05/podcast-welche-schulen-brauchen-die-kinder-von-heute/",
        woerter: 7496,
        ocr: false,
    },
    Eintrag {
        datum: "05.10.2021",
        titel: "Podcast: Patchworkfamilien und die häufigsten Fehler",
        url: "https://adhs.expert/2021/10/05/podcast-patchworkfamilien-und-die-haeufigsten-fehler/",
        woerter: 7545,
        ocr: false,
    },
    Eintrag {
        datum: "05.10.2021",
        titel: "Podcast: Woher kommt die Schizophrenie?",
        url: "https://adhs.expert/2021/10/05/podcast-woher-kommt-die-schizophrenie/",
        woerter: 7916,
        ocr: false,
    },
    Eintrag {
        datum: "05.10.2021",
        titel: "Warum fallen Menschen mit ADS und ADHS schneller in eine Depression, wie kommen sie wieder heraus?",
        url: "https://adhs.expert/2021/10/05/warum-fallen-menschen-mit-ads-und-adhs-schneller-in-eine-depression-wie-kommen-sie-wieder-heraus/",
        woerter: 11732,
        ocr: false,
    },
    Eintrag {
        datum: "14.09.2021",
        titel: "Prävention durch richtig Handeln im kritischen Augenblick",
        url: "https://adhs.expert/2021/09/14/praevention-durch-richtig-handeln-im-kritischen-augenblick-2/",
        woerter: 30275,
        ocr: false,
    },
    Eintrag {
        datum: "28.07.2021",
        titel: "Woher kommt die Schizophrenie?",
        url: "https://adhs.expert/2021/07/28/woher-kommt-die-schizophrenie/",
        woerter: 7916,
        ocr: false,
    },
    Eintrag {
        datum: "12.07.2021",
        titel: "Welche Schulen brauchen die Kinder von heute?",
        url: "https://adhs.expert/2021/07/12/welche-schulen-brauchen-die-kinder-von-heute/",
        woerter: 7496,
        ocr: false,
    },
    Eintrag {
        datum: "10.05.2021",
        titel: "Richtig Handeln im kritischen Augenblick",
        url: "https://adhs.expert/2021/05/10/richtig-handeln-im-kritischen-augenblick/",
        woerter: 30275,
        ocr: false,
    },
    Eintrag {
        datum: "05.05.2021",
        titel: "Was braucht es für die Ausbildung unserer nächsten Generation?",
        url: "https://adhs.expert/2021/05/05/was-braucht-es-fuer-die-ausbildung-unserer-naechsten-generation/",
        woerter: 7979,
        ocr: false,
    },
    Eintrag {
        datum: "18.03.2021",
        titel: "Postpartale Psychose, Depression, Borderline Störung, Sucht, psychische kranke Eltern und die Auswirkung auf die Kinder – Mütterberaterinnen, Teil 2",
        url: "https://adhs.expert/2021/03/18/postpartale-psychose-depression-borderline-stoerung-sucht-psychische-kranke-eltern-und-die-auswirkung-auf-die-kinder-muetterberaterinnen-teil-2/",
        woerter: 19815,
        ocr: false,
    },
    Eintrag {
        datum: "18.03.2021",
        titel: "Postpartale Psychose, Depression, Borderline Störung, Sucht, psychische kranke Eltern und die Auswirkung auf die Kinder – Mütterberaterinnen, Teil 1",
        url: "https://adhs.expert/2021/03/18/postpartale-psychose-depression-borderline-stoerung-sucht-psychische-kranke-eltern-und-die-auswirkung-auf-die-kinder-muetterberaterinnen-teil-1/",
        woerter: 23996,
        ocr: false,
    },
    Eintrag {
        datum: "18.03.2021",
        titel: "Umgang mit der Gefühlswelt bei ADHS in der Pubertät, Teil 2",
        url: "https://adhs.expert/2021/03/18/umgang-mit-der-gefuehlswelt-bei-adhs-in-der-pubertaet-teil-2/",
        woerter: 9116,
        ocr: false,
    },
    Eintrag {
        datum: "18.03.2021",
        titel: "Umgang mit der Gefühlswelt bei ADHS in der Pubertät, Teil 1",
        url: "https://adhs.expert/2021/03/18/umgang-mit-der-gefuehlswelt-bei-adhs-in-der-pubertaet-teil-1/",
        woerter: 8326,
        ocr: false,
    },
    Eintrag {
        datum: "18.03.2021",
        titel: "Diskussion zum Thema „Loslassen“, Frauenmorgen Muri",
        url: "https://adhs.expert/2021/03/18/diskussion-loslassen-frauenmorgen-muri/",
        woerter: 5861,
        ocr: false,
    },
    Eintrag {
        datum: "18.03.2021",
        titel: "Frauenmorgen Muri zum Thema „Loslassen“",
        url: "https://adhs.expert/2021/03/18/frauenmorgen-muri-zum-thema-loslassen/",
        woerter: 8480,
        ocr: false,
    },
    Eintrag {
        datum: "18.03.2021",
        titel: "Adoleszenz – Heranwachsen",
        url: "https://adhs.expert/2021/03/18/adoleszenz-teil-2/",
        woerter: 8266,
        ocr: false,
    },
    Eintrag {
        datum: "18.03.2021",
        titel: "Adoleszenz – Heranwachsen, Teil 1",
        url: "https://adhs.expert/2021/03/18/adoleszenz-teil-1/",
        woerter: 8081,
        ocr: false,
    },
    Eintrag {
        datum: "15.03.2021",
        titel: "Prävention durch richtig Handeln im kritischen Augenblick",
        url: "https://adhs.expert/2021/03/15/praevention-durch-richtig-handeln-im-kritischen-augenblick/",
        woerter: 30275,
        ocr: false,
    },
    Eintrag {
        datum: "08.03.2021",
        titel: "Gespräch zwischen Schizophrenie-Experten",
        url: "https://adhs.expert/2021/03/08/gespraech-zwischen-schizophrenie-experten/",
        woerter: 5811,
        ocr: false,
    },
    Eintrag {
        datum: "01.03.2021",
        titel: "Somatoforme Schmerzstörung",
        url: "https://adhs.expert/2021/03/01/somatoforme-schmerzstoerung/",
        woerter: 7250,
        ocr: false,
    },
    Eintrag {
        datum: "31.01.2021",
        titel: "Austausch von Erfahrungswissen aus dem praktischen Alltag",
        url: "https://adhs.expert/2021/01/31/austausch-von-erfahrungswissen-aus-dem-praktischen-alltag/",
        woerter: 6719,
        ocr: false,
    },
    Eintrag {
        datum: "23.12.2020",
        titel: "Weiterbildung zum Thema ADHS/ADS für Eltern, Lehrer, Betreuungspersonen der Schule Weinberg-Turner",
        url: "https://adhs.expert/2020/12/23/weiterbildung-zum-thema-adhs-ads-fuer-eltern-lehrer-betreuungspersonen-der-schule-weinberg-turner/",
        woerter: 5598,
        ocr: false,
    },
    Eintrag {
        datum: "15.12.2020",
        titel: "What you don’t use, you will loose. What fires together, wires together.",
        url: "https://adhs.expert/2020/12/15/what-you-dont-use-you-will-loose-what-fires-together-wires-together/",
        woerter: 7834,
        ocr: false,
    },
    Eintrag {
        datum: "12.12.2020",
        titel: "Wozu Störefriede und Eigenbrötler?",
        url: "https://adhs.expert/2020/12/12/wozu-stoerefriede-und-eigenbroetler/",
        woerter: 6666,
        ocr: false,
    },
    Eintrag {
        datum: "08.12.2020",
        titel: "Warum fallen Menschen mit ADHS häufiger in eine Depression und wie kommen sie wieder raus?",
        url: "https://adhs.expert/2020/12/08/warum-fallen-menschen-mit-adhs-haeufiger-in-eine-depression-und-wie-kommen-sie-wieder-raus/",
        woerter: 323,
        ocr: true,
    },
    Eintrag {
        datum: "01.12.2020",
        titel: "Warum der Stillstand in der Psychiatrie?",
        url: "https://adhs.expert/2020/12/01/warum-der-stillstand-in-der-psychiatrie/",
        woerter: 8009,
        ocr: false,
    },
    Eintrag {
        datum: "30.11.2020",
        titel: "Verlässliche Bindungen in der Kinderbetreuung",
        url: "https://adhs.expert/2020/11/30/verlaessliche-bindungen-in-der-kinderbetreuung/",
        woerter: 10087,
        ocr: false,
    },
    Eintrag {
        datum: "29.11.2020",
        titel: "AD(H)S als Hintergrund psychischer und körperlicher Krankheiten, Ideen für Prävention",
        url: "https://adhs.expert/2020/11/29/adhs-als-hintergrund-psychischer-und-koerperlicher-krankheiten-ideen-fuer-praevention/",
        woerter: 6811,
        ocr: false,
    },
    Eintrag {
        datum: "17.09.2020",
        titel: "Schulverweigerung bei Kindern mit ADHS und Lernstörungen",
        url: "https://adhs.expert/2020/09/17/schulverweigerung-bei-kindern-mit-adhs-und-lernstoerungen-2/",
        woerter: 12280,
        ocr: false,
    },
    Eintrag {
        datum: "17.04.2020",
        titel: "Versteckte Kosten",
        url: "https://adhs.expert/2020/04/17/versteckte-kosten/",
        woerter: 892,
        ocr: false,
    },
    Eintrag {
        datum: "17.10.2019",
        titel: "Kooperation statt gehorsam",
        url: "https://adhs.expert/2019/10/17/kooperation-statt-gehorsam/",
        woerter: 1620,
        ocr: false,
    },
    Eintrag {
        datum: "10.10.2019",
        titel: "Ronni Rocket – Wie das ADHS siegt und wie es scheitert",
        url: "https://adhs.expert/2019/10/10/ronni-rocket-wie-das-adhs-siegt-und-wie-es-scheitert/",
        woerter: 297,
        ocr: false,
    },
    Eintrag {
        datum: "26.06.2019",
        titel: "Trauma und Traumatherapie",
        url: "https://adhs.expert/2019/06/26/trauma-und-traumatherapie/",
        woerter: 9414,
        ocr: false,
    },
    Eintrag {
        datum: "13.03.2019",
        titel: "Sucht und Flucht in die digitale Welt",
        url: "https://adhs.expert/2019/03/13/sucht-und-flucht-in-die-digitale-welt/",
        woerter: 8488,
        ocr: false,
    },
    Eintrag {
        datum: "12.11.2018",
        titel: "Rolle der Frau in der heutigen Gesellschaft",
        url: "https://adhs.expert/2018/11/12/rolle-der-frau-in-der-heutigen-gesellschaft/",
        woerter: 102,
        ocr: false,
    },
    Eintrag {
        datum: "01.11.2018",
        titel: "Angehörigen Gruppe 2019",
        url: "https://adhs.expert/2018/11/01/angehoerigen-gruppe-2019/",
        woerter: 146,
        ocr: true,
    },
    Eintrag {
        datum: "01.11.2018",
        titel: "Gruppe für AD(H)S-Betroffene und Bezugspersonen wie Eltern, Partner, Lehrer, Lehrmeister, Vorgesetzte",
        url: "https://adhs.expert/2018/11/01/gruppe-fuer-adhs-betroffene-und-bezugspersonen-wie-eltern-partner-lehrer-lehrmeister-vorgesetzte-2/",
        woerter: 148,
        ocr: true,
    },
    Eintrag {
        datum: "20.10.2018",
        titel: "ADHS und Erziehung",
        url: "https://adhs.expert/2018/10/20/adhs-und-erziehung/",
        woerter: 11569,
        ocr: false,
    },
    Eintrag {
        datum: "16.10.2018",
        titel: "Emotionale Monsterwelle",
        url: "https://adhs.expert/2018/10/16/emotionale-monsterwelle/",
        woerter: 1232,
        ocr: false,
    },
    Eintrag {
        datum: "20.09.2018",
        titel: "Einladung zum Jubiläumsanlass 20 Jahre VASK Schweiz",
        url: "https://adhs.expert/2018/09/20/einladung-zum-jubilaeumsanlass-20-jahre-vask-schweiz/",
        woerter: 405,
        ocr: false,
    },
    Eintrag {
        datum: "05.07.2017",
        titel: "“Bindung – was die Welt zusammenhält“",
        url: "https://adhs.expert/2017/07/05/bindung-was-die-welt-zusammenhaelt/",
        woerter: 144,
        ocr: false,
    },
    Eintrag {
        datum: "17.04.2017",
        titel: "Muttersprache, Vatersprache",
        url: "https://adhs.expert/2017/04/17/muttersprache_vatersprache/",
        woerter: 6899,
        ocr: false,
    },
    Eintrag {
        datum: "07.03.2017",
        titel: "Gewalt in Familie und Beziehungen",
        url: "https://adhs.expert/2017/03/07/gewalt-in-familie-und-beziehungen/",
        woerter: 302,
        ocr: false,
    },
    Eintrag {
        datum: "08.02.2017",
        titel: "Spannungsfeld zwischen Psychologie, Religion und sozialer Verantwortung",
        url: "https://adhs.expert/2017/02/08/spannungsfeld-zwischen-psychologie-religion-und-sozialer-verantwortung/",
        woerter: 209,
        ocr: false,
    },
    Eintrag {
        datum: "26.01.2017",
        titel: "Cannabis und Schizophrenie",
        url: "https://adhs.expert/2017/01/26/cannabis-und-schizophrenie/",
        woerter: 1123,
        ocr: false,
    },
    Eintrag {
        datum: "30.10.2016",
        titel: "ADHS und Psychose",
        url: "https://adhs.expert/2016/10/30/adhs-und-psychose/",
        woerter: 5770,
        ocr: false,
    },
    Eintrag {
        datum: "03.09.2016",
        titel: "Ablösungsprobleme aus der Drei-Generationenperspektive",
        url: "https://adhs.expert/2016/09/03/abloesungsprobleme-aus-der-drei-generationenperspektive/",
        woerter: 3625,
        ocr: false,
    },
    Eintrag {
        datum: "13.06.2016",
        titel: "Jugendliche zwischen Stuhl und Bank beim Berufseinstieg",
        url: "https://adhs.expert/2016/06/13/jugendliche-zwischen-stuhl-und-bank-beim-berufseinstieg/",
        woerter: 275,
        ocr: false,
    },
    Eintrag {
        datum: "13.06.2016",
        titel: "Diplom- und Abschlussfeier Mütterberaterinnen 2016",
        url: "https://adhs.expert/2016/06/13/diplom-und-abschlussfeier-muetterberaterinnen-2016/",
        woerter: 360,
        ocr: false,
    },
    Eintrag {
        datum: "18.05.2016",
        titel: "Vom Genotyp zum Phaenotyp",
        url: "https://adhs.expert/2016/05/18/vom-genotyp-zum-phaenotyp/",
        woerter: 2133,
        ocr: false,
    },
    Eintrag {
        datum: "04.05.2016",
        titel: "PSYCHOTHERAPIE UND BERATUNG  Franziska Knapp",
        url: "https://adhs.expert/2016/05/04/psychotherapie-und-beratung-franziska-knapp/",
        woerter: 127,
        ocr: false,
    },
    Eintrag {
        datum: "21.04.2016",
        titel: "Psychotherapie und Coaching",
        url: "https://adhs.expert/2016/04/21/psychotherapie-und-coaching/",
        woerter: 280,
        ocr: false,
    },
    Eintrag {
        datum: "19.04.2016",
        titel: "Tod in der Familie",
        url: "https://adhs.expert/2016/04/19/tod-in-der-familie/",
        woerter: 800,
        ocr: false,
    },
    Eintrag {
        datum: "11.04.2016",
        titel: "Die Pubertät",
        url: "https://adhs.expert/2016/04/11/die_pubertaet/",
        woerter: 7804,
        ocr: false,
    },
    Eintrag {
        datum: "02.12.2015",
        titel: "Perfektionismus und Prokrastination",
        url: "https://adhs.expert/2015/12/02/perfektionismus-und-prokrastination/",
        woerter: 131,
        ocr: false,
    },
    Eintrag {
        datum: "01.09.2015",
        titel: "Engagement für die Arbeitsintegration",
        url: "https://adhs.expert/2015/09/01/engagement-fuer-die-arbeitsintegration/",
        woerter: 408,
        ocr: true,
    },
    Eintrag {
        datum: "31.05.2015",
        titel: "Buch Rezension ADHS und Schizophrenie",
        url: "https://adhs.expert/2015/05/31/buch-rezension-adhs-und-schizophrenie/",
        woerter: 157,
        ocr: true,
    },
    Eintrag {
        datum: "29.03.2015",
        titel: "Jeder Hundertste erkrankt an Schizophrenie",
        url: "https://adhs.expert/2015/03/29/jeder-hundertste-erkrankt-an-schizophrenie/",
        woerter: 2016,
        ocr: false,
    },
    Eintrag {
        datum: "20.01.2015",
        titel: "Lasst sie pubertieren!",
        url: "https://adhs.expert/2015/01/20/lasst-sie-pubertieren/",
        woerter: 1562,
        ocr: false,
    },
    Eintrag {
        datum: "07.09.2014",
        titel: "Religion",
        url: "https://adhs.expert/2014/09/07/religion/",
        woerter: 11675,
        ocr: false,
    },
    Eintrag {
        datum: "15.06.2014",
        titel: "Gesellschaft unter Hochdruck – was macht dies mit unserer Gesundheit",
        url: "https://adhs.expert/2014/06/15/gesellschaft-unter-hochdruck-was-macht-dies-mit-unserer-gesundheit/",
        woerter: 28576,
        ocr: false,
    },
    Eintrag {
        datum: "11.04.2014",
        titel: "Schizophrenie – Ein Tsunami für Familie und Umgebung",
        url: "https://adhs.expert/2014/04/11/schizophrenie-ein-tsunami-fur-familie-und-umgebung/",
        woerter: 10426,
        ocr: false,
    },
    Eintrag {
        datum: "06.04.2014",
        titel: "Pubertät, eine Zerreissprobe für die  Eltern-Kind-Beziehung",
        url: "https://adhs.expert/2014/04/06/pubertat-eine-zerreissprobe-fur-die-eltern-kind-beziehung/",
        woerter: 7483,
        ocr: false,
    },
    Eintrag {
        datum: "12.01.2014",
        titel: "Burnout bei pflegenden Angehörigen – Fragile AG SO 18.11.13",
        url: "https://adhs.expert/2014/01/12/burnout-bei-pflegenden-angehorigen-fragile-ag-so-18-11-13/",
        woerter: 12371,
        ocr: false,
    },
    Eintrag {
        datum: "21.09.2013",
        titel: "Postnatale Depression und Wochenbettpsychose",
        url: "https://adhs.expert/2013/09/21/postnatale-depression-und-wochenbettpsychose/",
        woerter: 26587,
        ocr: false,
    },
    Eintrag {
        datum: "23.09.2012",
        titel: "Paardynamik bei Erwachsenen mit ADHS",
        url: "https://adhs.expert/2012/09/23/paardynamik-bei-erwachsenen-mit-adhs/",
        woerter: 9784,
        ocr: false,
    },
    Eintrag {
        datum: "30.08.2012",
        titel: "Familientherapie bei Schizophreniekranken",
        url: "https://adhs.expert/2012/08/30/familientherapie-bei-schizophrenie-kranken/",
        woerter: 11833,
        ocr: false,
    },
    Eintrag {
        datum: "10.12.2011",
        titel: "Systemischer Umgang mit psychisch Kranken",
        url: "https://adhs.expert/2011/12/10/systemischer-umgang-mit-psychisch-kranken/",
        woerter: 8228,
        ocr: false,
    },
    Eintrag {
        datum: "01.05.2011",
        titel: "Geschwisterliebe Geschwisterstreit, 30.4.2011",
        url: "https://adhs.expert/2011/05/01/geschwisterliebe-geschwisterstreit-30-4-2011/",
        woerter: 10902,
        ocr: false,
    },
    Eintrag {
        datum: "24.10.2010",
        titel: "Jugendliche mit ADHS – Unterstützung im Übergang von der Schule ins Berufsleben",
        url: "https://adhs.expert/2010/10/24/jugendliche-mit-adhs-unterstutzung-im-ubergang-von-der-schule-ins-berufsleben/",
        woerter: 10107,
        ocr: false,
    },
];
